<?php
/**
 * Copyright © Resurs Bank AB. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Resursbank\Ordermanagement\Block\Adminhtml\Sales\Order\View\Info\PaymentHistory;

/** @var PaymentHistory $block */
/** @var Escaper $escaper */
/** @var SecureHtmlRenderer $secureRenderer */

$widget = $block->getWidget();

?>

<?php if ($widget !== null): ?>
    <?=
    /* @noEscape  */
    $secureRenderer->renderTag(
        tagName: 'script',
        attributes: [],
        content: $widget->js,
        textContent: false
    )
    ?>
    <?=
    /* @noEscape  */
    $secureRenderer->renderTag(
        tagName: 'style',
        attributes: [],
        content: $widget->css,
        textContent: true
    )
    ?>
    <?=
    $escaper->escapeHtml(
        data: $widget->content,
        allowedTags: $widget::getTagNames(content: $widget->content)
    )
    ?>
<?php endif; ?>
