<?php
/**
 * Copyright © Resurs Bank AB. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Resursbank\Ecom\Lib\Model\Callback\Enum\CallbackType;
use Resursbank\Ordermanagement\Block\Adminhtml\System\Config\Callback\Listing;

/**
 * @var Listing $block
 * @var Escaper $escaper
 */
?>

<h3><?= $escaper->escapeHtml(data: __('Registered Callbacks')) ?></h3>
<div style="max-width: 290px; overflow-x: scroll;">
        <p style="font-weight: bold;">[AUTHORIZATION]</p>
        <p style="margin-bottom:10px; padding-bottom:10px; border-bottom:1px dashed #c0c0c0;">
            <?= $escaper->escapeHtml(
                data: $this->callbackHelper->urlCallbackTemplate(strtolower(string: CallbackType::AUTHORIZATION->value))
            ) ?>
        </p>
        <p style="font-weight: bold;">[MANAGEMENT]</p>
        <p style="margin-bottom:10px; padding-bottom:10px; border-bottom:1px dashed #c0c0c0;">
            <?= $escaper->escapeHtml(
                data: $this->callbackHelper->urlCallbackTemplate(strtolower(string: CallbackType::MANAGEMENT->value))
            ) ?>
        </p>
</div>
