<?php
/**
 * Copyright © Resurs Bank AB. All rights reserved.
 * See LICENSE for license details.
 */

use Magento\Framework\Escaper;
use Resursbank\Ordermanagement\Block\Adminhtml\Sales\Order\View\Info\PaymentInformation;
use Resursbank\Ordermanagement\ViewModel\Adminhtml\Sales\Order\View\Info\PaymentInformation as ViewModel;

?>
<?php
/** @var $block PaymentInformation */
/** @var $viewModel ViewModel */
/** @var $escaper Escaper */
/** @noinspection PhpUndefinedMethodInspection */
$viewModel = $block->getViewModel();
$viewModel->setOrder(
    $viewModel->getOrder(
        (int)$block->getRequest()->getParam('order_id')
    )
);
?>
<?php if ($viewModel->isEnabled()): ?>
    <?php if (empty($viewModel->getPaymentInformation())): ?>
        <div class="field-group">
            <p class="error-message">
                <?= $escaper->escapeHtml(__('Payment information could not be retrieved from Resursbank.')) ?>
            </p>
        </div>
    <?php else: ?>
        <section class="admin__page-section resursbank-ordermanagement-payment-information">
            <div class="admin__page-section-title">
                <span class="title">
                    <?= $escaper->escapeHtml(__('Payment Information')) ?>
                </span>
                <div class="resursbank-logo">
                    <div class="img"></div>
                </div>
            </div>
            <div class="admin__page-section-content">

                <?php // Payment information?>
                <div class="admin__page-section-item">
                    <div class="admin__page-section-item-content">
                        <table class="admin__table-secondary">
                            <tbody>
                                <tr>
                                    <th>
                                        <?= $escaper->escapeHtml(__('Payment ID')) ?>
                                    </th>
                                    <td>
                                        <?= $escaper->escapeHtml($viewModel->getPaymentId()) ?>
                                    </td>
                                </tr>
                                <tr>
                                    <th>
                                        <?= $escaper->escapeHtml(__('Order Total')) ?>
                                    </th>
                                    <td>
                                        <span class="price">
                                            <?= $escaper->escapeHtml($viewModel->getPaymentTotal()) ?>
                                        </span>
                                    </td>
                                </tr>
                                <tr>
                                    <th>
                                        <?= $escaper->escapeHtml(__('Limit')) ?>
                                    </th>
                                    <td>
                                        <span class="price">
                                            <?= $escaper->escapeHtml($viewModel->getPaymentLimit()) ?>
                                        </span>
                                    </td>
                                </tr>
                                <tr>
                                    <th>
                                        <?= $escaper->escapeHtml(__('Status')) ?>

                                    </th>
                                    <td>
                                        <?= $escaper->escapeHtml(__($viewModel->getPaymentStatus())) ?>

                                    </td>
                                </tr>
                                <tr>
                                    <th>
                                        <?= $escaper->escapeHtml(__('Frozen')) ?>
                                    </th>
                                    <td>
                                        <?= $escaper->escapeHtml(__(($viewModel->isFrozen() ? 'Yes' : 'No'))) ?>
                                    </td>
                                </tr>
                                <tr>
                                    <th>
                                        <?= $escaper->escapeHtml(__('Fraud?')) ?>
                                    </th>
                                    <td>
                                        <?= $escaper->escapeHtml(__(($viewModel->isFraud() ? 'Yes' : 'No'))) ?>
                                    </td>
                                </tr>
                                <tr>
                                    <th>
                                        <?= $escaper->escapeHtml(__('Payment method')) ?>
                                    </th>
                                    <td>
                                        <?= $escaper->escapeHtml(__($viewModel->getPaymentMethodName())) ?>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>

                <?php // Customer information?>
                <div class="admin__page-section-item">
                    <div class="admin__page-section-item-title">
                        <span class="title">
                            <?= $escaper->escapeHtml(__('Customer Information')) ?>
                        </span>
                    </div>
                    <div class="admin__page-section-item-content">
                        <table class="admin__table-secondary">
                            <tbody>
                                <tr>
                                    <th>
                                        <?= $escaper->escapeHtml(__('Name')) ?>
                                    </th>
                                    <td>
                                        <?= $escaper->escapeHtml($viewModel->getCustomerName()) ?>
                                    </td>
                                </tr>
                                <tr>
                                    <th>
                                        <?= $escaper->escapeHtml(__('Address')) ?>

                                    </th>
                                    <td>
                                        <?php foreach ($viewModel->getCustomerAddress() as $value): ?>
                                            <?= $escaper->escapeHtml($value) ?>
                                            <br />
                                        <?php endforeach; ?>
                                    </td>
                                </tr>
                                <tr>
                                    <th>
                                        <?= $escaper->escapeHtml(__('Telephone')) ?>
                                    </th>
                                    <td>
                                        <?= $escaper->escapeHtml($viewModel->getCustomerTelephone()) ?>
                                    </td>
                                </tr>
                                <tr>
                                    <th>
                                        <?= $escaper->escapeHtml(__('Email')) ?>

                                    </th>
                                    <td>
                                        <?= $escaper->escapeHtml($viewModel->getCustomerEmail()) ?>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </section>
    <?php endif; ?>
<?php endif; ?>
