<?php
/**
 * Copyright © Resurs Bank AB. All rights reserved.
 * See LICENSE for license details.
 */
?>
<?php
/**
 * @var Magento\Sales\Block\Order\View $block
 */

/** @var Magento\Sales\Model\Order $order */
$order = $block->getOrder();

/** @var Resursbank\Ordermanagement\ViewModel\Adminhtml\Sales\Order\View\Info\PaymentHistory $viewModel */
/** @noinspection PhpUndefinedMethodInspection */
$viewModel = $block->getViewModel();
?>

<?php if ($viewModel->visible($order)) : ?>
    <div id="resursbank-ordermanagement-order-view-payment-history"
         data-bind="scope: 'payment-history'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>

    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "payment-history": {
                            "component": "Resursbank_Ordermanagement/js/sales/order/view/info/payment-history",
                            "events": <?php echo $viewModel->getTableDataFromOrder($order); ?>,
                            "heading": "<?php echo $viewModel->getHeading($order); ?>"
                        }
                    }
                }
            }
        }
    </script>
<?php endif; ?>
