<?php
/**
 * Copyright © Resurs Bank AB. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magento\Sales\Model\Order;
use Resursbank\Ordermanagement\ViewModel\Adminhtml\Sales\Order\View\Info\PaymentHistory;

/** @var Template $block */
/** @var Error $viewModel */
/** @var Escaper $escaper */
/** @noinspection PhpUndefinedMethodInspection */
/** @phpstan-ignore-next-line */
$viewModel = $block->getViewModel();

/** @var Order $order */
$order = $block->getOrder();

/** @var PaymentHistory $viewModel */
/** @noinspection PhpUndefinedMethodInspection */
$viewModel = $block->getViewModel();
?>

<?php if ($viewModel->visible($order)): ?>
    <div id="resursbank-ordermanagement-order-view-payment-history"
         data-bind="scope: 'payment-history'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>

    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "payment-history": {
                            "component": "Resursbank_Ordermanagement/js/sales/order/view/info/payment-history",
                            "events": <?= /* @noEscape */ $viewModel->getTableDataFromOrder($order) ?>,
                            "heading": "<?= $escaper->escapeHtml($viewModel->getHeading($order)) ?>"
                        }
                    }
                }
            }
        }
    </script>
<?php endif; ?>
