<?php
/**
 * Copyright © Resurs Bank AB. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

/** @var PaymentInformation $block */
/** @var Escaper $escaper */

use Resursbank\Ordermanagement\Block\Adminhtml\Sales\Order\View\Info\PaymentInformation;
use Magento\Framework\Escaper;

$html = isset($block) ? $block->getWidgetHtml() : '';
$css = isset($block) ? $block->getWidgetCss() : '';
?>

<?php if ($html === ''): ?>
    <div class="field-group">
        <p class="error-message">
            <?= $escaper->escapeHtml(data: __('Payment information could not be retrieved from Resurs Bank.'))  ?>
        </p>
    </div>
<?php else: ?>
    <style>
        <?= $css ?>
    </style>
    <?= $html ?>
<?php endif; ?>
