<?php
/**
 * Copyright © Resurs Bank AB. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Resursbank\Ecom\Lib\Model\Callback\Enum\CallbackType;
use Resursbank\Ordermanagement\Block\Adminhtml\System\Config\Ecom\CallbackList;

/**
 * @var CallbackList $block
 * @var Escaper $escaper
 */
?>

<div style="max-width: 600px; overflow-x: scroll;">
    <p style="font-weight: bold;">[AUTHORIZATION]</p>
    <p style="margin-bottom:10px; padding-bottom:10px; border-bottom:1px dashed #c0c0c0;">
        <?= $escaper->escapeHtml(
            data: $block->getCallbackUrl(type: strtolower(string: CallbackType::AUTHORIZATION->value))
        ) ?>
    </p>
    <p style="font-weight: bold;">[MANAGEMENT]</p>
    <p style="margin-bottom:10px; padding-bottom:10px; border-bottom:1px dashed #c0c0c0;">
        <?= $escaper->escapeHtml(
            data: $block->getCallbackUrl(type: strtolower(string: CallbackType::MANAGEMENT->value))
        ) ?>
    </p>
</div>
