<?php
/**
 * Copyright © Resurs Bank AB. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Resursbank\Ordermanagement\Block\Adminhtml\System\Config\CallbackList\Ecom;

/**
 * @var Ecom $block
 * @var SecureHtmlRenderer $secureRenderer
 * @var Escaper $escaper
 */

$widget = $block->getWidget();
?>

<?php if ($widget !== null): ?>
    <?=
    /* @noEscape */
    $secureRenderer->renderTag(
        tagName: 'style',
        attributes: [],
        content: $widget->css,
        textContent: true
    )
    ?>

    <?=
    $escaper->escapeHtml(data: $widget->content, allowedTags: ['div', 'p'])
    ?>
<?php endif; ?>
